### PR TITLE
Tweak to tick label positioning  - h:m: on left side, not right

### PR DESCRIPTION
**Pull request by keflavich**
Should solve https://github.com/aplpy/aplpy/issues/258, e.g.:

image

### CODE REVIEW

**Comment by astrofrog** [comment]
@keflavich - thanks! However, I think we need to preserve previous behavior otherwise it might end up breaking a lot of layouts. Can you make it a tick label option?

**Comment by keflavich** [comment]
Could you suggest where that belongs in the api?  New methodthat replaces
the wcsformatter or part of another that already sets the wcsformatter?

**Comment by astrofrog** [comment]
I would suggest ``TickLabels.set_full_label_side('left'/'right')`` defaulting to 'right'. APLpy is a bit hacky so it passes tick label parameters (for example ``apl_label_form``) by setting attributes on the formatter so you can do something similar. No need to define new methods or classes.

**Comment by astrofrog** [comment]
I've opened an issue over at the Astropy repo: https://github.com/astropy/astropy/issues/7571 - closing this in the mean time.

**Pull request closed without merging**
