### PR TITLE
Allow rotation of a rectangle around center

### PR DESCRIPTION
**Pull request by bryanmiller**
This allows one to pass a rotation angle to show_rectangles. The rectangle are rotated around the center position.

### CODE REVIEW

**Comment by astrofrog** [comment]
Thanks! (and sorry for the long delay in merging!)

**Comment by banados** [comment]
This somehow does not work yet in 

    aplpy.__version__ 
    2.0.3

    matplotlib.__version__
    3.0.3 

The rotation is not around the center but around the lower left coordinate

**Comment by banados** [comment]
It works if l1428-1437 are modified as follows:

    xp = x - w / 2.
    yp = y - h / 2.
    radeg = np.pi / 180
    xr = (xp - x)*np.cos((angle)*radeg) - (yp - y)*np.sin((angle)*radeg) + x
    yr = (xp - x)*np.sin((angle)*radeg) + (yp - y)*np.cos((angle)*radeg) + y

    patches = []
        for i in range(len(xr)):
            patches.append(Rectangle((xr[i], yr[i]), width=w[i], height=h[i], angle=a[i]))

**Comment by GiantMolecularCloud** [comment]
Rotation around the wrong axis can be quite annoying. Thanks @banados for the fix!
I submitted a pull request with the proposed changes in aplpy/aplpy/pull/428

**Pull request merged**
