### PR TITLE
In show_regions, allow WCS "headers"

### PR DESCRIPTION
**Pull request by keflavich**
Apparently the "header" can be passed to show_regions as a WCS object.  This PR accommodates that use case

### CODE REVIEW

**Comment by paulray** [comment]
Thank you! I found this PR and it fixed the problem I was having trying to lay regions on my image!
I would get an error like this:
```
  File "PSCmap.py", line 17, in <module>
    fig.show_regions('PSC.reg')
  File "<string>", line 2, in show_regions
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aplpy/decorators.py", line 25, in _auto_refresh
    return f(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aplpy/regions.py", line 65, in show_regions
    PC, TC = ds9(region_file, wcs.WCS(self._header).sub([wcs.WCSSUB_CELESTIAL]), **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aplpy/regions.py", line 103, in ds9
    rrim = rr.as_imagecoord(header)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyregion/core.py", line 70, in as_imagecoord
    shape_list, comment_list = zip(*list(r))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyregion/ds9_region_parser.py", line 187, in sky_to_image
    new_coords = convert_to_imagecoord(shape, header)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyregion/wcs_converter.py", line 81, in convert_to_imagecoord
    new_wcs = WCS(header)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astropy/wcs/wcs.py", line 398, in __init__
    for dict_key in orig_header.keys():
AttributeError: 'WCS' object has no attribute 'keys'
```
Applying this patch makes it work!  I recommend merging.

**Comment by astrofrog** [comment]
@keflavich - can you rebase as the tests should be fixed in master?

**Comment by keflavich** [comment]
still have one failure: https://travis-ci.org/aplpy/aplpy/jobs/393421921

**Comment by astrofrog** [comment]
That will get fixed imminently in astropy-dev

**Pull request merged**
