### PR TITLE
Fixing configparser imports for python 3.5.2

### PR DESCRIPTION
**Pull request by bsipocz**

### CODE REVIEW

**Comment by cdeil** [comment]
There's this error in most travis-ci builds:
https://travis-ci.org/aplpy/aplpy/jobs/141775625#L458
```
The following specifications were found to be in conflict:
  - matplotlib 1.4.** -> numpy 1.10*|1.6*|1.7*|1.8*|1.9*
  - matplotlib 1.4.** -> python 2.6*|3.3*|3.4*|3.5*
  - numpy 1.11*
```

@bsipocz @astrofrog - Time to drop some old supported versions of APLPy dependencies?

**Comment by bsipocz** [comment]
Ohh, this is great.

This stopped working as https://github.com/astropy/ci-helpers/pull/103 now enforces to use the real "stable" for astropy and numpy, and  not whatever comes up from conda. 

I see two options to solve this, if mpl 1.4 is still need to be fixed: a) use numpy 1.10 instead of "stable" b) rethink the "stable" install in ci-helpers, e.g. allow to downgrade numpy in certain situations. And of course option c) is to use mpl 1.5 :)

For APLpy I would go with option a), but equally happy to do option b) if you come up with a robust approach.

**Comment by astrofrog** [comment]
For APLpy and WCSAxes, we deliberately need to test with different versions. I'm in favor of just doing the easy thing and doing a)

**Comment by astrofrog** [comment]
We can remove support for Python 2.6 btw

**Comment by bsipocz** [comment]
Done

**Comment by astrofrog** [comment]
@bsipocz - thanks!

**Pull request merged**
